services:
  postgres:
    image: postgres:16-alpine
    container_name: cleverlog_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: cleverlog
      POSTGRES_USER: cleverlog_user
      POSTGRES_PASSWORD: cleverlog_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
